name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  echo-learn-ga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "I learn github actions"